#!/bin/bash
# Job name:
#SBATCH --job-name=julia
#
# Account:
#
# Partition:
#
# Request one node:
#SBATCH --nodes=1
# Specify one task:
#SBATCH --ntasks-per-node=1
#
# Number of processors for single task needed for use case (example):
#SBATCH --cpus-per-task=1
#
# Wall clock limit:
#SBATCH --time=4:00:00
#
## Command(s) to run (example):
./gpu_benchmark.sh H100
# ./benchmark.sh
# ./bench_cpu_h100.sh 
# source venv/bin/activate
# python3 generate_figures_gpu.py
echo "FINISHED RUNNING ALL JOBS"
